<?php

namespace SkyHub\Api\DataTransformers\Catalog\Product\Attribute;

use SkyHub\Api\DataTransformers\DataTransformerAbstract;

/**
 * BSeller Platform | B2W - Companhia Digital
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  SkuHub
 * @package   SkuHub
 *
 * @copyright Copyright (c) 2018 B2W Digital - BSeller Platform. (http://www.bseller.com.br).
 *
 * @author    Tiago Sampaio <tiago.sampaio@e-smart.com.br>
 */
class Update extends DataTransformerAbstract
{
    
    /**
     * Attribute constructor.
     *
     * @param string $code
     * @param string $label
     * @param array  $options
     */
    public function __construct($code, $label, array $options = [])
    {
        $this->setOutputData([
             'attribute' => [
                 'label'   => $label,
                 'options' => $options
             ]
        ]);
        
        parent::__construct();
    }
}
