<?php
/**
 * BSeller Platform | B2W - Companhia Digital
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  ${MAGENTO_MODULE_NAMESPACE}
 * @package   ${MAGENTO_MODULE_NAMESPACE}_${MAGENTO_MODULE}
 *
 * @copyright Copyright (c) 2018 B2W Digital - BSeller Platform. (http://www.bseller.com.br)
 *
 * @author    Tiago Sampaio <tiago.sampaio@e-smart.com.br>
 */

namespace SkyHub\Api\Handlers\Catalog\Product;

use SkyHub\Api\Handlers\AbstractHandler;

class AttributeHandler extends AbstractHandler
{
    
    public function createAttribute($code, $label, array $options = [])
    {
    
    }
    
    
    
    public function updateAttribute($code, $label, array $options = [])
    {
    
    }

}
