<?php

namespace SkyHub\Api\Handler\Response;

use Psr\Http\Message\ResponseInterface;

/**
 * BSeller Platform | B2W - Companhia Digital
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  SkuHub
 * @package   SkuHub
 *
 * @copyright Copyright (c) 2018 B2W Digital - BSeller Platform. (http://www.bseller.com.br).
 *
 * @author    Tiago Sampaio <tiago.sampaio@e-smart.com.br>
 */
interface HandlerInterfaceSuccess extends HandlerInterface
{

    /**
     * HandlerInterface constructor.
     *
     * @param ResponseInterface $response
     */
    public function __construct(ResponseInterface $response);
    
    
    /**
     * @return ResponseInterface
     */
    public function httpResponse();


    /**
     * @return mixed
     */
    public function body();
    
    
    /**
     * @return int|null
     */
    public function bodySize();


    /**
     * @return mixed
     */
    public function headers();


    /**
     * @return mixed
     */
    public function statusCode();


    /**
     * @return mixed
     */
    public function protocolVersion();
    
    
    /**
     * @return string
     */
    public function reasonPhrase();
}
