<?php
/**
 * B2W Digital - Companhia Digital
 *
 * Do not edit this file if you want to update this SDK for future new versions.
 * For support please contact the e-mail bellow:
 *
 * sdk@e-smart.com.br
 *
 * @category  SkyHub
 * @package   SkyHub
 *
 * @copyright Copyright (c) 2018 B2W Digital - BSeller Platform. (http://www.bseller.com.br).
 *
 * @author    Bruno Gemelli <bruno.gemelli@e-smart.com.br>
 */

namespace SkyHub\Api\EntityInterface\Shipment;

use SkyHub\Api\EntityInterface\EntityAbstract;
use SkyHub\Api\Handler\Request\Shipment\PlpHandler;

class Plp extends EntityAbstract
{

    /**
     * @param string $id
     *
     * @return $this
     */
    public function setId($id)
    {
        $this->data['id'] = (string) $id;
        return $this;
    }


    /**
     * @return string
     */
    public function getId()
    {
        return $this->getData('id');
    }


    /**
     * @return \SkyHub\Api\Handler\Response\HandlerInterface
     */
    public function plps()
    {
        /** @var PlpHandler $handler */
        $handler = $this->requestHandler();
        return $handler->plps();
    }


    /**
     * @return \SkyHub\Api\Handler\Response\HandlerInterface
     */
    public function ordersReadyToGroup()
    {
        /** @var PlpHandler $handler */
        $handler = $this->requestHandler();
        return $handler->ordersReadyToGroup();
    }


    /**
     * @return \SkyHub\Api\Handler\Response\HandlerInterface
     */
    public function ungroup()
    {
        /** @var PlpHandler $handler */
        $handler = $this->requestHandler();
        return $handler->ungroup($this->getId());
    }
}
