<?php

namespace SkyHub\Api\DataTransformer\Catalog\Product\Variation;

use SkyHub\Api\DataTransformer\Builders;
use SkyHub\Api\DataTransformer\DataTransformerAbstract;

/**
 * BSeller Platform | B2W - Companhia Digital
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  SkuHub
 * @package   SkuHub
 *
 * @copyright Copyright (c) 2018 B2W Digital - BSeller Platform. (http://www.bseller.com.br).
 *
 * @author    Tiago Sampaio <tiago.sampaio@e-smart.com.br>
 */
class Create extends DataTransformerAbstract
{

    use Builders;


    /**
     * CreateVariation constructor.
     *
     * @param string $sku
     * @param string $qty
     * @param string $ean
     * @param array  $images
     * @param array  $specifications
     */
    public function __construct($sku, $qty = null, $ean = null, array $images = [], array $specifications = [])
    {
        $variation['sku'] = (string) $sku;

        if ($qty) {
            $variation['qty'] = (int) $qty;
        }

        if ($ean) {
            $variation['ean'] = (string) $ean;
        }

        /** Build product variation's images. */
        $this->buildProductImages($variation, (array) $images);

        /** Build product variation's specifications. */
        $this->buildProductSpecifications($variation, (array) $specifications);

        $this->setOutputData(['variation' => $variation]);

        parent::__construct();
    }
}
