<?php

namespace SkyHub\Api\DataTransformer\Sales\Order;

use SkyHub\Api\DataTransformer\DataTransformerAbstract;

/**
 * BSeller Platform | B2W - Companhia Digital
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  SkuHub
 * @package   SkuHub
 *
 * @copyright Copyright (c) 2018 B2W Digital - BSeller Platform. (http://www.bseller.com.br).
 *
 * @author    Tiago Sampaio <tiago.sampaio@e-smart.com.br>
 */
class Invoice extends DataTransformerAbstract
{

    /**
     * Attribute constructor.
     *
     * @param string $status
     * @param string $invoiceKey
     */
    public function __construct($status, $invoiceKey)
    {
        $this->setOutputData([
            'status'  => $status,
            'invoice' => [
                'key' => $invoiceKey
            ],
        ]);

        parent::__construct();
    }
}
