<?php

namespace SkyHub\Api\DataTransformer\Sales\Order;

use SkyHub\Api\DataTransformer\DataTransformerAbstract;

/**
 * BSeller Platform | B2W - Companhia Digital
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  SkuHub
 * @package   SkuHub
 *
 * @copyright Copyright (c) 2018 B2W Digital - BSeller Platform. (http://www.bseller.com.br).
 *
 * @author    Tiago Sampaio <tiago.sampaio@e-smart.com.br>
 */
class ShipmentException extends DataTransformerAbstract
{

    /**
     * ShipmentException constructor.
     *
     * @param string $orderId
     * @param string $datetime
     * @param string $observation
     */
    public function __construct($orderId, $datetime, $observation)
    {
        /**
         * @todo Convert the $datetime to the correct format: '2012-10-06T04:13:00-03:00'
         */
        $shipmentException = [
            'shipment_exception' => [
                'occurrence_date' => $datetime,
                'observation'     => $observation
            ]
        ];

        $this->setOutputData($shipmentException);

        parent::__construct();
    }
}
