<?php
/**
 * B2W Digital - Companhia Digital
 *
 * Do not edit this file if you want to update this SDK for future new versions.
 * For support please contact the e-mail bellow:
 *
 * sdk@e-smart.com.br
 *
 * @category  SkyHub
 * @package   SkyHub
 *
 * @copyright Copyright (c) 2018 B2W Digital - BSeller Platform. (http://www.bseller.com.br).
 *
 * @author    Bruno Gemelli <bruno.gemelli@e-smart.com.br>
 */

namespace SkyHub\Api\DataTransformer\Shipment\Plp;

use SkyHub\Api\DataTransformer\DataTransformerAbstract;

class Group extends DataTransformerAbstract
{

    /**
     * PLP orders grouper constructor.
     *
     * @param array $orders
     */
    public function __construct(array $orders = [])
    {
        $this->setOutputData([
            'order_remote_codes' => $orders
        ]);

        parent::__construct();
    }
}
