<?php
/**
 * B2W Digital - Companhia Digital
 *
 * Do not edit this file if you want to update this SDK for future new versions.
 * For support please contact the e-mail bellow:
 *
 * sdk@e-smart.com.br
 *
 * @category  SkuHub
 * @package   SkuHub
 *
 * @copyright Copyright (c) 2018 B2W Digital - BSeller Platform. (http://www.bseller.com.br).
 *
 * @author    Tiago Sampaio <tiago.sampaio@e-smart.com.br>
 */

namespace SkyHub\Api\DataTransformer\Catalog\Category;

use SkyHub\Api\DataTransformer\DataTransformerAbstract;

class Update extends DataTransformerAbstract
{
    
    /**
     * Attribute constructor.
     *
     * @param string $code
     * @param string $name
     */
    public function __construct($code, $name)
    {
        $this->setOutputData([
             'category' => [
                 'name' => $name
             ]
        ]);
        
        parent::__construct();
    }
}
