<?php

namespace SkyHub\Api\EntityInterface;

use SkyHub\Api\Helpers;
use SkyHub\ApiInterface;

/**
 * BSeller Platform | B2W - Companhia Digital
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  SkuHub
 * @package   SkuHub
 *
 * @copyright Copyright (c) 2018 B2W Digital - BSeller Platform. (http://www.bseller.com.br).
 *
 * @author    Tiago Sampaio <tiago.sampaio@e-smart.com.br>
 */
abstract class EntityAbstract implements EntityInterface
{
    
    use Helpers;
    
    protected $data = [];
    
    /** @var ApiInterface */
    protected $api;
    
    
    /**
     * EntityAbstract constructor.
     *
     * @param ApiInterface $api
     */
    public function __construct(ApiInterface $api = null)
    {
        if (!empty($api)) {
            $this->api = $api;
        }
    }
    
    
    /**
     * @param string $key
     *
     * @return array|bool|mixed|string
     */
    public function getData($key = null, $default = null)
    {
        if (is_null($key)) {
            return $this->data;
        }
        
        return $this->arrayExtract($this->data, $key, $default);
    }
    
    
    /**
     * @param string       $key
     * @param string|array $value
     *
     * @return $this
     */
    public function setData($key, $value)
    {
        $this->data[$key] = $value;
        return $this;
    }
    
    
    /**
     * @return array
     */
    public function export()
    {
        return $this->getData();
    }
}
