<?php

/**
 * BSeller Platform | B2W - Companhia Digital
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  SkuHubTest
 * @package   SkuHubTest
 *
 * @copyright Copyright (c) 2021 B2W Digital - BSeller Platform. (http://www.bseller.com.br).
 *
 */

namespace SkyHubTest\Api\DataTransformer\Catalog\Product\Stock;

use PHPUnit\Framework\TestCase;
use SkyHub\Api\DataTransformer\Catalog\Product\Stock\Update as DataTransformerStock;

/**
 * UpdateTest class
 */
class UpdateTest extends TestCase
{
    /**
     * @test
     */
    public function checkDataTransformeStock()
    {
        $qty = 10;
        $expected = [
            'product' => [
                'qty' => $qty
            ]
        ];
        $data = new DataTransformerStock($qty);
        $actual = $data->output();

        $this->assertEquals($expected, $actual);
    }
}