<?php
/**
 * BSeller Platform | B2W - Companhia Digital
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  ${MAGENTO_MODULE_NAMESPACE}
 * @package   ${MAGENTO_MODULE_NAMESPACE}_${MAGENTO_MODULE}
 *
 * @copyright Copyright (c) 2018 B2W Digital - BSeller Platform. (http://www.bseller.com.br)
 *
 * @author    Tiago Sampaio <tiago.sampaio@e-smart.com.br>
 */

include __DIR__ . '/../../api.php';

/** @var \SkyHub\Api\EntityInterface\Catalog\Product\Attribute $entityInterface */
$entityInterface = $api->productAttribute()
                       ->entityInterface();

$entityInterface->setCode('color')
                ->setLabel('Color')
                ->addOption('Blue')
                ->addOption('White')
                ->addOption('Green')
                ->addOption('Yellow');

/**
 * Create an Attribute
 *
 * @var SkyHub\Api\Handler\Response\HandlerInterface $response
 */
$response = $entityInterface->create();

/**
 * Update an Attribute
 *
 * @var SkyHub\Api\Handler\Response\HandlerInterface $response
 */
$response = $entityInterface->create();
