<?php
/**
 * BSeller Platform | B2W - Companhia Digital
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  ${MAGENTO_MODULE_NAMESPACE}
 * @package   ${MAGENTO_MODULE_NAMESPACE}_${MAGENTO_MODULE}
 *
 * @copyright Copyright (c) 2018 B2W Digital - BSeller Platform. (http://www.bseller.com.br)
 *
 * @author    Tiago Sampaio <tiago.sampaio@e-smart.com.br>
 */

include __DIR__ . '/../../api.php';

/** @var SkyHub\Api\Handler\Request\Catalog\Product\AttributeHandler $requestHandler */
$requestHandler = $api->productAttribute();

/**
 * Create an Attribute
 * @var SkyHub\Api\Handler\Response\HandlerInterface $response
 */
$response = $requestHandler->create('color', 'Color', ['Blue', 'White', 'Green', 'Yellow']);


/**
 * Update an Attribute
 */
$response = $requestHandler->update('color', 'Color', ['Blue', 'White', 'Green', 'Yellow', 'Orange']);
