<?php
/**
 * BSeller Platform | B2W - Companhia Digital
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  Skyhub
 * @package   Skyhub
 *
 * @copyright Copyright (c) 2018 B2W Digital - BSeller Platform. (http://www.bseller.com.br)
 *
 * @author    Bruno Gemelli <bruno.gemelli@e-smart.com.br>
 */

include __DIR__ . '/../api.php';

/** @var \SkyHub\Api\Handler\Request\Shipment\PlpHandler $requestHandler */
$requestHandler = $api->plp();


/**
 * GET A LIST OF PLP's
 * @var SkyHub\Api\Handler\Response\HandlerInterface $response
 */
$response = $requestHandler->plps();

