<?php
/**
 * B2W Digital - Companhia Digital
 *
 * Do not edit this file if you want to update this SDK for future new versions.
 * For support please contact the e-mail bellow:
 *
 * sdk@e-smart.com.br
 *
 * @category  SkuHub
 * @package   SkuHub
 *
 * @copyright Copyright (c) 2018 B2W Digital - BSeller Platform. (http://www.bseller.com.br).
 *
 * @author    Tiago Sampaio <tiago.sampaio@e-smart.com.br>
 */

namespace SkyHub\Api\Log\TypeInterface;

interface TypeRequestInterface extends TypeInterface
{
    
    /**
     * @param string $method
     *
     * @return $this
     */
    public function setMethod($method = null);
    
    
    /**
     * @param string $uri
     *
     * @return $this
     */
    public function setUri($uri = null);
    
    
    /**
     * @param array $requestOptions
     *
     * @return $this
     */
    public function setOptions(array $requestOptions = []);
}
