<?php

namespace SkyHub\Api\Log\TypeInterface;

/**
 * BSeller Platform | B2W - Companhia Digital
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  SkuHub
 * @package   SkuHub
 *
 * @copyright Copyright (c) 2018 B2W Digital - BSeller Platform. (http://www.bseller.com.br).
 *
 * @author    Tiago Sampaio <tiago.sampaio@e-smart.com.br>
 */
interface TypeRequestInterface extends TypeInterface
{
    
    /**
     * @param string $method
     *
     * @return $this
     */
    public function setMethod($method = null);
    
    
    /**
     * @param string $uri
     *
     * @return $this
     */
    public function setUri($uri = null);
    
    
    /**
     * @param array $requestOptions
     *
     * @return $this
     */
    public function setOptions(array $requestOptions = []);
}
