<?php

namespace SkyHub\Api\DataTransformers\Catalog\Category;

use SkyHub\Api\DataTransformers\DataTransformerAbstract;

/**
 * BSeller Platform | B2W - Companhia Digital
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  SkuHub
 * @package   SkuHub
 *
 * @copyright Copyright (c) 2018 B2W Digital - BSeller Platform. (http://www.bseller.com.br).
 *
 * @author    Tiago Sampaio <tiago.sampaio@e-smart.com.br>
 */
class Create extends DataTransformerAbstract
{

    /**
     * Attribute constructor.
     *
     * @param string $code
     * @param string $name
     */
    public function __construct($code, $name)
    {
        $this->setOutputData([
            'category' => [
                'code' => $code,
                'name' => $name
            ]
        ]);

        parent::__construct();
    }
}
