<?php
/**
 * BSeller Platform | B2W - Companhia Digital
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  ${MAGENTO_MODULE_NAMESPACE}
 * @package   ${MAGENTO_MODULE_NAMESPACE}_${MAGENTO_MODULE}
 *
 * @copyright Copyright (c) 2018 B2W Digital - BSeller Platform. (http://www.bseller.com.br)
 *
 * @author    Tiago Sampaio <tiago.sampaio@e-smart.com.br>
 */

namespace SkyHub\Api\Handlers;

use SkyHub\Api\DataTransformers\DataTransformerInterface;
use SkyHub\Api\ServiceInterface;
use SkyHub\ApiInterface;

abstract class AbstractHandler implements HandlerInterface
{
    
    /** @var ApiInterface */
    private $api;
    
    /** @var DataTransformerInterface */
    protected $_transformer = null;
    
    /** @var string */
    protected $_transformerClass = null;
    
    
    /**
     * AbstractHandler constructor.
     *
     * @param ApiInterface $api
     */
    public function __construct(ApiInterface $api)
    {
        $this->api = $api;
    }
    
    
    /**
     * @return DataTransformerInterface
     */
    protected function transformer()
    {
        if (empty($this->_transformerClass)) {
            $this->_transformer = new $this->_transformerClass();
        }
        
        return $this->_transformer;
    }
    
    
    /**
     * @return ServiceInterface
     */
    protected function service()
    {
        return $this->api->service();
    }
    
    
    /**
     * @return ApiInterface
     */
    public function api()
    {
        return $this->api;
    }

}
