<?php
/**
 * BSeller Platform | B2W - Companhia Digital
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  ${MAGENTO_MODULE_NAMESPACE}
 * @package   ${MAGENTO_MODULE_NAMESPACE}_${MAGENTO_MODULE}
 *
 * @copyright Copyright (c) 2018 B2W Digital - BSeller Platform. (http://www.bseller.com.br)
 *
 * @author    Tiago Sampaio <tiago.sampaio@e-smart.com.br>
 */
namespace SkyHub\Api\Handlers;

use SkyHub\Api\Handlers\Catalog\CategoryHandler;
use SkyHub\Api\Handlers\Catalog\Product\AttributeHandler;
use SkyHub\Api\Handlers\Catalog\ProductHandler;

trait Getters
{
    
    /**
     * @return AttributeHandler
     */
    public function productAttribute()
    {
        return new AttributeHandler($this);
    }
    
    
    /**
     * @return ProductHandler
     */
    public function product()
    {
        return new ProductHandler($this);
    }
    
    
    /**
     * @return CategoryHandler
     */
    public function category()
    {
        return new CategoryHandler($this);
    }
    
}
