<?php

/**
 * BSeller Platform | B2W - Companhia Digital
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  SkuHubTest
 * @package   SkuHubTest
 *
 * @copyright Copyright (c) 2021 B2W Digital - BSeller Platform. (http://www.bseller.com.br).
 *
 */

namespace SkyHubTest\Api\DataTransformer\Catalog\Product\Price;

use PHPUnit\Framework\TestCase;
use SkyHub\Api\DataTransformer\Catalog\Product\Price\Update as DataTransformerPrice;

/**
 * UpdateTest class
 */
class UpdateTest extends TestCase
{
    /**
     * @test
     */
    public function checkDataTransformePricePromotionPrice()
    {
        $price = 1.00;
        $promotionalPrice = 0.90;
        $expected = [
            'product' => [
                'price' => $price,
                'promotional_price' => $promotionalPrice 
            ]
        ];
        
        $data = new DataTransformerPrice($price, $promotionalPrice);
        $actual = $data->output();
        $this->assertEquals($expected, $actual);
    }

    /**
     * @test
     */
    public function checkDataTransformeOnlyPrice()
    {
        $price = 1.00;
        $expected = [
            'product' => [
                'price' => $price
            ]
        ];
        
        $data = new DataTransformerPrice($price);
        $actual = $data->output();
        $this->assertEquals($expected, $actual);
    }
}
