<?php
/**
 * BSeller Platform | B2W - Companhia Digital
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  SkyHub
 * @package   SkyHub
 *
 * @copyright Copyright (c) 2018 B2W Digital - BSeller Platform. (http://www.bseller.com.br)
 *
 * @author    Tiago Sampaio <tiago.sampaio@e-smart.com.br>
 */

$email   = 'teste.sdk@skyhub.com.br';
$apiKey  = 'ddRTGUrf_bho17FooTjC';

/** @var \SkyHub\Api $api */
$api = new SkyHub\Api($email, $apiKey);
