<?php
/**
 * BSeller Platform | B2W - Companhia Digital
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  SkyHub
 * @package   SkyHub
 *
 * @copyright Copyright (c) 2018 B2W Digital - BSeller Platform. (http://www.bseller.com.br)
 *
 * @author    Bruno Gemelli <bruno.gemelli@e-smart.com.br>
 */

$email   = 'teste.sdk@skyhub.com.br';
$apiKey  = 'ddRTGUrf_bho17FooTjC';

/** @var SkyHub\Api\ $servicePdf */
$servicePdf = new SkyHub\Api\Service\ServicePdf(null);

/** @var \SkyHub\Api $api2 */
$apiPdf = new SkyHub\Api($email, $apiKey, null, null, $servicePdf);
