<?php
/**
 * BSeller Platform | B2W - Companhia Digital
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  SkyHub
 * @package   SkyHub
 *
 * @copyright Copyright (c) 2018 B2W Digital - BSeller Platform. (http://www.bseller.com.br)
 *
 * @author    Tiago Sampaio <tiago.sampaio@e-smart.com.br>
 */

require_once dirname(__FILE__) . '/../vendor/autoload.php';

/**
 * All the information provided here is not real.
 *
 * First account call.
 */
$email  = 'account1@skyhub.com.br';
$apiKey = '9999999999999999999999';

$api = new \SkyHub\Api($email, $apiKey);

/** @var \SkyHub\Api\Handler\Request\Sales\OrderHandler $requestHandler */
$requestHandler = $api->order();
$order = $requestHandler->order('TEST-1524688765999');

/**
 * Second account call.
 */
$email  = 'account2@skyhub.com.br';
$apiKey = '7777777777777777777777';

$api->setAuthentication($email, $apiKey);

$order = $requestHandler->order('TEST-1524688765777');
