<?php
/**
 * BSeller Platform | B2W - Companhia Digital
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  SkyHub
 * @package   SkyHub
 *
 * @copyright Copyright (c) 2021 B2W Digital - BSeller Platform. (http://www.bseller.com.br)
 */
if ($_FILES) {
    require_once dirname(__FILE__) . '/../vendor/autoload.php';
    $email   = 'teste@teste.com';
    $apiKey  = '123terreddrrre';
    $service = new SkyHub\Api\Service\ServiceMultipart(null);
    /** @var \SkyHub\Api $api */
    $api = new SkyHub\Api($email, $apiKey, null, null, $service);

    try{
        $result = $api->order()->invoiceB2wDirect(
            'Teste-1234',
            $_POST['volqty'],
            '2021-01-27T12:30:00-03:00',
            $_FILES['file']['tmp_name'],
            $_FILES['file']['name']
        );
        var_dump($result->export());
    } catch (\Exception $e) {
        echo $e->getMessage()."\n";
    }
}
?>
<form action="" method="POST" enctype="multipart/form-data">
<input type="file" name="file" />
<input type="text" name="volqty" />
<input type="submit" value="Send" />
</form>