<?php
/**
 * B2W Digital - Companhia Digital
 *
 * Do not edit this file if you want to update this SDK for future new versions.
 * For support please contact the e-mail bellow:
 *
 * sdk@e-smart.com.br
 *
 * @category  SkuHub
 * @package   SkuHub
 *
 * @copyright Copyright (c) 2018 B2W Digital - BSeller Platform. (http://www.bseller.com.br).
 *
 * @author    Tiago Sampaio <tiago.sampaio@e-smart.com.br>
 */

namespace SkyHub\Api\DataTransformer\Sales\Order\Status;

use SkyHub\Api\DataTransformer\DataTransformerAbstract;

class Create extends DataTransformerAbstract
{

    /**
     * Create constructor.
     *
     * @param string $code
     * @param string $label
     * @param string $type
     */
    public function __construct($code, $label, $type)
    {
        $this->setOutputData([
            'status' => [
                'code'  => $code,
                'label' => $label,
                'type'  => $type
            ]
        ]);

        parent::__construct();
    }
}
