<?php

namespace SkyHub\Api\DataTransformer\Sales\Order\Status;

/**
 * BSeller Platform | B2W - Companhia Digital
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  SkuHub
 * @package   SkuHub
 *
 * @copyright Copyright (c) 2018 B2W Digital - BSeller Platform. (http://www.bseller.com.br).
 *
 * @author    Tiago Sampaio <tiago.sampaio@e-smart.com.br>
 */
class Update extends Create
{

    /**
     * Create constructor.
     *
     * @param string $code
     * @param string $label
     * @param string $type
     */
    public function __construct($code, $label, $type)
    {
        parent::__construct($code, $label, $type);
    }
}
