<?php

/**
 * B2W Digital - Companhia Digital
 *
 * Do not edit this file if you want to update this SDK for future new versions.
 * For support please contact the e-mail bellow:
 *
 * sdk@e-smart.com.br
 *
 * @category  SkyHub
 * @package   SkyHub
 *
 * @copyright Copyright (c) 2021 B2W Digital - BSeller Platform. (http://www.bseller.com.br).
 *
 */

namespace SkyHub\Api\Handler\Request\Catalog\Product;

use SkyHub\Api\EntityInterface\Catalog\Product\Price;
use SkyHub\Api\Handler\Request\HandlerAbstract;
use SkyHub\Api\DataTransformer\Catalog\Product\Price\Update as UpdateTransformer;

class PriceHandler extends HandlerAbstract
{
    /** @var string */
    protected $baseUrlPath = '/products';

    /**
     * @param string $sku
     * @param float $price
     * @param float $promotionalPrice
     * @param array $platformPrices
     * @return \SkyHub\Api\Handler\Response\HandlerInterface
     */
    public function update(
        $sku,
        $price,
        $promotionalPrice = null,
        $platformPrices = []
    ) {
        $transformer = new UpdateTransformer(
            $price,
            $promotionalPrice,
            $platformPrices
        );

        $body = $transformer->output();

        /** @var \SkyHub\Api\Handler\Response\HandlerInterface $responseHandler */
        $responseHandler = $this->service()->put($this->baseUrlPath($sku), $body);
        return $responseHandler;
    }

    /**
     * @return Price
     */
    public function entityInterface()
    {
        return new Price($this);
    }
}
