<?php

/**
 * B2W Digital - Companhia Digital
 *
 * Do not edit this file if you want to update this SDK for future new versions.
 * For support please contact the e-mail bellow:
 *
 * sdk@e-smart.com.br
 *
 * @category  SkyHub
 * @package   SkyHub
 *
 * @copyright Copyright (c) 2021 B2W Digital - BSeller Platform. (http://www.bseller.com.br).
 *
 */

namespace SkyHub\Api\Handler\Request\Catalog\Product;

use SkyHub\Api\EntityInterface\Catalog\Product\Stock;
use SkyHub\Api\Handler\Request\HandlerAbstract;
use SkyHub\Api\DataTransformer\Catalog\Product\Stock\Update as UpdateTransformer;

class StockHandler extends HandlerAbstract
{
    /** @var string */
    protected $baseUrlPath = '/products';

    /**
     * @param string $sku
     * @param int    $qty
     *
     * @return \SkyHub\Api\Handler\Response\HandlerInterface
     */
    public function update(
        $sku,
        $qty
    ) {
        $transformer = new UpdateTransformer($qty);

        $body = $transformer->output();

        /** @var \SkyHub\Api\Handler\Response\HandlerInterface $responseHandler */
        $responseHandler = $this->service()->put($this->baseUrlPath($sku), $body);
        return $responseHandler;
    }


    /**
     * @return Stock
     */
    public function entityInterface()
    {
        return new Stock($this);
    }
}