<?php

/**
 * B2W Digital - Companhia Digital
 *
 * Do not edit this file if you want to update this SDK for future new versions.
 * For support please contact the e-mail bellow:
 *
 * sdk@e-smart.com.br
 *
 * @category  SkyHub
 * @package   SkyHub
 *
 * @copyright Copyright (c) 2021 B2W Digital - BSeller Platform. (http://www.bseller.com.br).
 *
 */

namespace SkyHub\Api\EntityInterface\Catalog\Product;

use SkyHub\Api\EntityInterface\EntityAbstract;
use SkyHub\Api\Handler\Response\HandlerDefault;
use SkyHub\Api\Handler\Response\HandlerException;

class Price extends EntityAbstract
{
    /**
     * @param string $sku
     *
     * @return $this
     */
    public function setSku($sku)
    {
        $this->setData('sku', (string) $sku);
        return $this;
    }

    /**
     * @return string
     */
    public function getSku()
    {
        return (string) $this->getData('sku');
    }

    /**
     * @param float $price
     *
     * @return $this
     */
    public function setPrice($price)
    {
        $this->setData('price', $price);
        return $this;
    }

    /**
     * @return float
     */
    public function getPrice()
    {
        return (float) $this->getData('price');
    }

    /**
     * @param float $promotionalPrice
     *
     * @return $this
     */
    public function setPromotionalPrice($promotionalPrice)
    {
        $this->setData('promotional_price', $promotionalPrice);
        return $this;
    }

    /**
     * @return float
     */
    public function getPromotionalPrice()
    {
        return (float) $this->getData('promotional_price');
    }

    /**
     * @return HandlerDefault|HandlerException
     */
    public function update()
    {
        $this->validate();

        /** @var \SkyHub\Api\Handler\Request\Catalog\Product\PriceHandler $handler */
        $handler = $this->requestHandler();
        
        /** @var HandlerDefault|HandlerException $response */
        $response = $handler->update($this->getSku(), $this->getPrice(), $this->getPromotionalPrice());

        return $response;
    }
}
