<?php

/**
 * B2W Digital - Companhia Digital
 *
 * Do not edit this file if you want to update this SDK for future new versions.
 * For support please contact the e-mail bellow:
 *
 * sdk@e-smart.com.br
 *
 * @category  SkyHub
 * @package   SkyHub
 *
 * @copyright Copyright (c) 2021 B2W Digital - BSeller Platform. (http://www.bseller.com.br).
 *
 */

namespace SkyHub\Api\EntityInterface\Catalog\Product;

use SkyHub\Api\EntityInterface\EntityAbstract;
use SkyHub\Api\Handler\Response\HandlerDefault;
use SkyHub\Api\Handler\Response\HandlerException;

class Stock extends EntityAbstract
{
    /**
     * @param string $sku
     *
     * @return $this
     */
    public function setSku($sku)
    {
        $this->setData('sku', (string) $sku);
        return $this;
    }

    /**
     * @return string
     */
    public function getSku()
    {
        return (string) $this->getData('sku');
    }

    /**
     * @param int $qty
     *
     * @return $this
     */
    public function setQty($qty)
    {
        $this->setData('qty', $qty);
        return $this;
    }

    /**
     * @return int
     */
    public function getQty()
    {
        return (int) $this->getData('qty');
    }

    /**
     * @return HandlerDefault|HandlerException
     */
    public function update()
    {
        $this->validate();

        /** @var \SkyHub\Api\Handler\Request\Catalog\Product\StockHandler $handler */
        $handler = $this->requestHandler();
        
        /** @var HandlerDefault|HandlerException $response */
        $response = $handler->update($this->getSku(), $this->getQty());

        return $response;
    }
}
