<?php

namespace SkyHub\Api\EntityInterface\Catalog\Product;

use SkyHub\Api\EntityInterface\EntityAbstract;

/**
 * BSeller Platform | B2W - Companhia Digital
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  SkuHub
 * @package   SkuHub
 *
 * @copyright Copyright (c) 2018 B2W Digital - BSeller Platform. (http://www.bseller.com.br).
 *
 * @author    Tiago Sampaio <tiago.sampaio@e-smart.com.br>
 */
class Variation extends EntityAbstract
{
    
    use MutualMethods;
    
    
    /** @var array */
    protected $data = [];
    
    
    /**
     * Variation constructor.
     *
     * @param string $sku
     * @param int    $qty
     * @param string $ean
     */
    public function __construct($sku, $qty, $ean)
    {
        $this->setSku($sku);
        $this->setQty($qty);
        $this->setEan($ean);
        
        parent::__construct();
    }


    /**
     * @return bool
     */
    public function validate()
    {
        return true;
    }
}
