<?php
/**
 * BSeller Platform | B2W - Companhia Digital
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  SkyHub
 * @package   ${MAGENTO_MODULE_NAMESPACE}_${MAGENTO_MODULE}
 *
 * @copyright Copyright (c) 2018 B2W Digital - BSeller Platform. (http://www.bseller.com.br)
 *
 * @author    Tiago Sampaio <tiago.sampaio@e-smart.com.br>
 */
namespace SkyHub;

use SkyHub\Api\Connection;

class Api
{
    
    /** @var Connection */
    protected $_connection = null;
    
    
    /**
     * Api constructor.
     *
     * @param string $email
     * @param string $apiKey
     * @param string $token
     */
    public function __construct($email, $apiKey, $token)
    {
        $this->getConnection()
             ->init($email, $apiKey, $token);
    }
    
    
    /**
     * @return bool
     */
    public function hasConnection()
    {
        return $this->getConnection()
                    ->checkConnection();
    }
    
    
    /**
     * Gets a single connection instance.
     *
     * @return Connection
     */
    protected function getConnection()
    {
        if (null === $this->_connection) {
            $this->_connection = Connection::getInstance();
        }
    
        return $this->_connection;
    }

}
