<?php
/**
 * BSeller Platform | B2W - Companhia Digital
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  SkyHub
 * @package   ${MAGENTO_MODULE_NAMESPACE}_${MAGENTO_MODULE}
 *
 * @copyright Copyright (c) 2018 B2W Digital - BSeller Platform. (http://www.bseller.com.br)
 *
 * @author    Tiago Sampaio <tiago.sampaio@e-smart.com.br>
 */
namespace SkyHub;

use SkyHub\Api\Service;

class Api
{
    
    /** @var Service */
    protected $_connection = null;
    
    
    /**
     * Api constructor.
     *
     * @param string $email
     * @param string $apiKey
     * @param string $apiToken
     */
    public function __construct($email, $apiKey, $apiToken)
    {
        $this->getService()
             ->init($email, $apiKey, $apiToken);
    }
    
    
    /**
     * @return bool
     */
    public function checkService()
    {
        return $this->getService()
                    ->checkService();
    }
    
    
    /**
     * Gets a single connection instance.
     *
     * @return Service
     */
    public function getService()
    {
        if (null === $this->_connection) {
            $this->_connection = Service::getInstance();
        }
    
        return $this->_connection;
    }

}
