<?php
namespace SkyHub;

use SkyHub\Api\Service\ServiceInterface;

/**
 * BSeller Platform | B2W - Companhia Digital
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  SkuHub
 * @package   SkuHub
 *
 * @copyright Copyright (c) 2018 B2W Digital - BSeller Platform. (http://www.bseller.com.br).
 *
 * @author    Tiago Sampaio <tiago.sampaio@e-smart.com.br>
 */
interface ApiInterface
{
    
    /**
     * ApiInterface constructor.
     *
     * @param string                $baseUri
     * @param string                $email
     * @param string                $apiKey
     * @param string                $apiToken
     * @param ServiceInterface|null $apiService
     */
    public function __construct($baseUri, $email, $apiKey, $apiToken, ServiceInterface $apiService = null);
    
    
    /**
     * @return \SkyHub\Api\Service\ServiceInterface
     */
    public function service();
}
