<?php
/**
 * BSeller Platform | B2W - Companhia Digital
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  ${MAGENTO_MODULE_NAMESPACE}
 * @package   ${MAGENTO_MODULE_NAMESPACE}_${MAGENTO_MODULE}
 *
 * @copyright Copyright (c) 2018 B2W Digital - BSeller Platform. (http://www.bseller.com.br)
 *
 * @author    Tiago Sampaio <tiago.sampaio@e-smart.com.br>
 */

namespace SkyHub\Api;

use SkyHub\Api;

class ConnectionTest extends \PHPUnit\Framework\TestCase
{
    
    public function testHasConnection()
    {
        $api = new Api('test@teste.com.br', '', '');
        $this->assertTrue($api->hasConnection());
    }

}
